### ISSUE TITLE
Explorer missing an "Executable" account detail

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/explorer#127]

**Comment by jackcmay** [comment]
@jstarry fyi

**Comment by jstarry** [comment]
@jackcmay this is pretty tricky actually. Right now, the transaction details page is showing the "Readonly" and "Signer" tags by decoding the transaction message header. The "Program" is determined by decoding each instruction's program_id_index.

In order to show whether each account involved in an instruction is executable, we would need to fetch the info for all involved accounts. And that fetched state wouldn't necessarily match up with the state when the transaction was processed.

May I ask what prompted this issue? Seems to me that showing each instruction's specified program is sufficient. Is this related to cross program invocations?

**Comment by jstarry** [comment]
<img width="975" alt="Screen Shot 2020-05-22 at 6 45 21 PM" src="https://user-images.githubusercontent.com/1076145/82660141-65f99080-9c5c-11ea-81ab-b050269bd4f0.png">

Also, we already add the "Program" tag to the transaction accounts list.

**Comment by jackcmay** [comment]
What prompted it was my brain torqued a bit when I looked at the "Accounts" section.  When I think of "Accounts" I'm thinking of the state of the account on the chain, so executable tag seems a natural there and the lack makes me wonder.  Probably just bad context on my end since the whole page is in the context of the transaction.

What is the Raw Data?  Is that instruction data?  if so, maybe we should label it that and instead of base58 just list out the byte values?

**Comment by jstarry** [comment]
This is great feedback! I'll fix up the copy then 👍
