### ISSUE TITLE
[Bug] Warning message shown for a Token which misleads the audience

### ISSUE THREAD

**Issue by solankirohan** [solana-labs/explorer#229]
**Describe the bug**
After creating a spl-token by following the recommended steps like creating a metadatav2 instruction with valid token metadata format and a uri which points to a json file, explorer site shows a message - "Warning! Token names and logos are not unique. This token may have spoofed its name and logo to look like another token. Verify the token's mint address to ensure it is correct."

**To Reproduce**
1. Create an spl-token by following the steps mentioned [here](https://spl.solana.com/token#example-creating-your-own-fungible-token)
2. After successfully minting the token open the mint address in the [explorer](https://explorer.solana.com) site. 
3. Observe the Warning message in pink - "Warning! Token names and logos are not unique. This token may have spoofed its name and logo to look like another token. Verify the token's mint address to ensure it is correct."

**Example Links**
- https://explorer.solana.com/address/EZAxbt341NUi7MYCX6rUdiUS87A2Tycv2otfBBwRcGsa
- https://explorer.solana.com/address/o1Mw5Y3n68o8TakZFuGKLZMGjm72qv4JeoZvGiCLEvK

**Expected behavior**
If the metadata is provided with valid uri then explorer should **NOT** show the warning message.
Earlier it was required to register the token by raising a PR on the [registry](https://github.com/solana-labs/token-list) repo, but now this repo is EOL and it is now required to create a metadatav2 instruction with valid token metadata format and a uri which points to a json file. Hence, the newly created token should be treated same as any other token which is part of the initial registry list and should not show the warning message. This message misleads the token audience who may feel it could be an incorrect token. NOTE: No such message is shown on solscan site.

**Screenshots**
<img width="1188" alt="Screenshot 2023-03-12 at 8 50 22 PM" src="https://user-images.githubusercontent.com/6348477/224570436-4170da20-60a7-47a2-8361-22b0bd7ec85f.png">

**Additional context**

**Comment by codefuturance** [comment]
Hi, we are having the same issue here.  Our token is minted according to the standards provided in the EOL announcement of the SPL Token list repo. Our token has a valid token metadata format and a uri which points to a json file. But, the spoofed token warning message is displayed: 

https://explorer.solana.com/address/FEXoYTghBykVXy8Rvm7QSVEvC2NvucGJWTGipoPbyDi1/metadata

<img width="1230" alt="image" src="https://github.com/solana-labs/explorer/assets/88134160/5d5175f9-5e1f-46f7-beef-a38ffaab83e9">

Not sure what the problem is here, the PRs here #288 and #289 seem to merged to Master by  @steveluscher  but have they been deployed to production? 

Is is not better to completely remove this warning until a better verification paradigm is agreed upon ?

Thanks

**Comment by steveluscher** [comment]
The verification paradigm is ‘appearing in the Solflare Unified Token List,’ @codefuturance.

https://token-list-api.solana.cloud/v1/search?query=fexo&start=0&limit=1
