### ISSUE TITLE
Support multiple domain types

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/explorer#271]
Currently we only support Bonfida .sol domains, using the Bonfida SDK directly

I suggest that we use the [solana-wallet-names](https://github.com/portalpayments/solana-wallet-names) SDK from Portal Payments instead, which supports multiple domain types

This will give us support for many domain providers at once

As this SDK includes ANS addresses, this will also handle #205 (without favouring any provider) and supersede #236 with less code to maintain in Explorer.

**Comment by mikemaccana** [comment]
Author of solana-wallet-names here (I now work at Foundation). Definitely agree that supporting all name services rather than favoring Bonfida is good.

 - It would be reasonable to add a layer of caching, maybe 1 hour, so we don't bother upstream wallet name services.
 - If we decide to support multiple name services, we should let the various wallet services know we are intending on supporting their name services on the next wallet call.
