### ISSUE TITLE
[Bug] Distribution Tab Missing?

### ISSUE THREAD

**Issue by philetos** [solana-labs/explorer#285]
There was a Distribution Tab where we could view top token holders and the relative distribution. Is this intentionally missing now?

Seems like this was available in the old create react app implementation
```  
 {
      slug: "largest",
      title: "Distribution",
      path: "/largest",
 }
```

**Comment by mcintyre94** [comment]
I removed this because it wasn't working on mainnet. The JSON RPC function used for this is [`getTokenLargestAccounts`](https://docs.solana.com/api/http#gettokenlargestaccounts). The RPC provider that we're using for Explorer (and AFAICT, most RPC providers) don't index token accounts on mainnet:

```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32010,
        "message": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA excluded from account secondary indexes; this RPC method unavailable for key"
    },
    "id": "cf555c33-087d-419c-9dd3-36e5df2bf16f"
}
```

See related: https://github.com/solana-labs/solana-program-library/issues/2547 

Did you have a use case where this tab was providing useful data previously?

**Comment by philetos** [comment]
> Did you have a use case where this tab was providing useful data previously?

I am building an experience where the users earn various community tokens in their PDA Wallet...and expose a link to account on chain. From there it is nice to have top token distribution visible form associated Mint accounts for transparency. 
![IMG_5571](https://github.com/solana-labs/explorer/assets/794651/e781ae91-2297-42e7-b7f4-da238ead40dd)

![IMG_5572](https://github.com/solana-labs/explorer/assets/794651/07726529-31a1-42b8-af1f-11137b76980c)


Would be a nice way to encourage trust and we all looking to onboard "non" crypto natives :]
